### ISSUE TITLE
Odd Icon Behavior when Minimizing and then unminimizing.

### ISSUE THREAD

**Issue by rdlf4** [robint99/mate-dock-applet#158]
Hello there, Mate-Dock team!
I've been using Mate-dock since Linux Mint v19. On Linux Mint 18.1 I was used to using Avant-Window-Navigator, which no longer has its dependencies supported on Tara, and since I don't like the awful-old look of gnome-panel, I'm struggling with Mate-dock, which is why I'm here.
I've studied the README.md provided from this Github release (currently v0.86) and it states the only version compatible with the GTK3 version that comes with Linux Mint is v0.80 - but it mentions a link that points to v0.81 (?). Anyway, I downloaded the zip from 0.80 after removing the one that's on the software manager (from Linux Mint), which is v0.85.
But I've been experiencing the same issues described down below, regardless of which version:
*** Odd Icon Behavior
There are two main odd behaviors that I can reproduce. (You need to have 'Show Window' added to your panel).
Mate-dock Icon will not bring back up a window that has been minimized: All this one takes to reproduce is this: after logging in, open up three different applications. In my case, Firefox, Terminal and Text Editor. Then minimize all windows by clicking on 'Show/Hide Window' icon. Now, instead of clicking on the same icon again to bring all the windows back up, I choose to click on the Firefox icon first. It works, Firefox is maximized again. But as for the other applications, _Mate-dock will just flash the icon repeatedly as if it was calling for my attention, instead of bringing the window back up, forcing me to use Alt+Tab to get that window back up_ and kind of beats the purpose IMO.
This has been reproduced on v0.80; v0.85 (the one that is provided by Linux Mint 19's software manager) and v0.86 (currently the most up-to-date).
*** Odd Icon Behavior v2
Yeah, same problem but slightly different. Mate-dock will NOT display an icon on the panel _if the application in question is a Windows app running under Wine_ and this is all that it takes to reproduce it (you need to have Wine or Crossover (which is a trialware for 2 weeks) and Microsoft Office to experience this): open up a .docx file. That's it. You'll see the application maximized but it won't be listed on the panel, again forcing me into using Alt+Tab to get back to it. I tried everything in my mind to force Mate-dock into displaying the icon and so far I only managed to make it work.. kinda, like this:
After opening up a docx file, I clicked on 'Show/Hide Window' icon twice and that seems to make it display the icon, which looks like a gear. But then again, clicking on it either makes mate-dock confused, it acts as if the icon is a launcher and then open up Microsoft Office again with a blank page (v0.80, v0.85) or rather, keeps flashing continuously  forever, and does not minimize or maximize the window (v0.86).
-> I can confirm these behavior happen under Marco + Compositing and under Compiz. In other words, it doesn't matter which window manager you choose.
-> All the testing was made with Mate-dock compiled manually (for versions 0.80 and 0.86) with support for GTK3. I'm not sure whether Version 0.85 (comes with Linux Mint Tara 19) is GTK3 or not, as I don't recall whether it was mentioned under About and I'm using v0.86.

Please let me know if there are any files or Terminal commands whose output is required to further investigate this bug report. I'll be happy to provide them.

Thank you.

**Comment by robint99** [comment]
I've been looking into Odd Icon Behaviour v1 for a couple of days now and just can't seem to reproduce the problem. No matter what version of the applet I use (0.80, 0.85, 0.86) all of the apps that I try restore their windows correctly and their icon doesn't flash. I've tried this under Marco, Compton and Compiz and also on Ubuntu 18.04 as well as Mint 19. To help me try to understand what's going it would be helpful if you could do the following:

- remove the dock from the panel
- in a terminal run this command `python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py`
- add the dock to panel again

When you try to restore a window you should get output in the terminal like this:

`(dock_applet.py:24866): Wnck-WARNING **: 09:01:32.649: Received a timestamp of 0; window activation may not function properly`

So, you should get this at when you restore Firefox. Could you let me know if this also appears when you try to restore your terminal and text editor?

As for Odd Icon Behaviour v2 I haven't looked at this yet, mainly because I don't have a copy of Office I can install under Wine. Do you know of any other Window programs I can try (preferably free ones) which show the same problem in the dock?

Thanks.

P.S. I've updated README.md with info about using the applet on Mint 19.

**Comment by rdlf4** [comment]
@robin99 First of all, thank you for looking into this. I know I could have done much better by providing more details, but for now I'll show you this is a thing that does happen. Please take the time to watch this video, it won't take long (~8min): https://youtu.be/_YJTJJwceYw 


> When you try to restore a window you should get output in the terminal like this:
> 
> (dock_applet.py:24866): Wnck-WARNING **: 09:01:32.649: Received a timestamp of 0; window activation may not function properly
> 
> So, you should get this at when you restore Firefox. Could you let me know if this also appears when you try to restore your terminal and text editor?

I can confirm I get the same message for the Terminal and text editor. However, their icon just flashes but their window are not restored. This is my terminal output:

`(dock_applet.py:8060): Wnck-WARNING **: 05:26:20.640: Received a timestamp of 0; window activation may not function properly.`

I'm looking for and trying out some Windows applications that trigger the same issue. The video provided in this comment does show some more of it as well, using Word.
I'll edit this comment whenever I manage to find out something new/worth sharing.

Thanks.

**Comment by robint99** [comment]
Thanks to your video I was finally able to reproduce Odd Icon Behaviour v1. It seems to be something to do with Compiz and only on Mint (Ubuntu is ok). Anyway, I've just committed a fix for this which I've tested on VirtualBox and on real hardware and it works for me. However I'd be grateful if you could try it and confirm that Behaviour v1 has gone.  

I haven't had a chance to look Behaviour v2, but from your video it looks very like issue #139. The splash screen for apps would display in the dock, but the main window wouldn't. I committed a fix for this issue a few days ago, so as I don't again I'd be grateful if you try the latest code and see if Behaviour v2 still occurs for you.

Cheers.

**Comment by robint99** [comment]
For Ubuntu and Linux Mint I've written a makeshift program to automate the downloading and compiling of the applet. With Mint 19 it installs the very latest code from github.

To give it a try you can get it from [this](https://github.com/robint99/misc/blob/master/da_installer.py) link (right click and do 'save as'). To run it, open up a terminal, cd to the directory where you saved the file and do `python3 da_installer.py`

**Comment by robint99** [comment]
Everything continues to work for me, and since I've just released a new version of the applet including the fix,  I'll close this issue now.

**Comment by rdlf4** [comment]
I'm sorry, I've been too busy to come back with new reports and kinda left this to the side. Not intentional though. So yeah, as much as I don't have the intention to resurrect this thread, I guess it's simpler to post it here again instead of making a new thread when the issue discussed here is still the same.
I've posted another video for you with two more unresolved Mate-dock issues.
https://youtu.be/juoYfVXplUk
